version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      angular:
        patterns:
          - "angular*"
          - "@angular/*"
      general:
        patterns:
          - "*"
        exclude-patterns:
          - "angular*"
          - "@angular/*"
